docker-build:
  # Use the official docker image.
  image: registry.gitlab.com/mangoads/swarm-deploy-dind:v1.0
  stage: build
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.12-dind
  before_script:
    - apk update && apk add git
    - git fetch origin $CI_DEFAULT_BRANCH --tags
    - docker login -u tabenguyen -p b67e761c-b3db-454f-a043-a730289c9193
  script:
    - docker build -t tabenguyen/laravel-php-8.1:latest -f Dockerfile-php8.1-fpm-alpine .
    - docker push tabenguyen/laravel-php-8.1:latest