name: Build docker image

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - 
        name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile-php8.1-fpm-alpine
          push: true
          tags: tabenguyen/laravel-php:8.1
      -
        name: Build and push 7.4
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile-php7.4-fpm-alpine
          push: true
          tags: tabenguyen/laravel-php:7.4